### ISSUE TITLE
Parser fails when 2 links are in a paragraph

### ISSUE THREAD

**Issue by jm-nab** [MyPureCloud/knowledge-html-converter#2]
Example inputs:

```
const tests = [
  '<p><a href="https://url" rel="noopener noreferrer" target="_blank">Upgrading/Downgrading</a><a href="https://url"></a></p>',
  '<p><strong><u>Article Contents:</u></strong></p><ul><li><a href="#s">s</a></li><li><a href="#w">w</a></li><li><a href="#v">v</a></li><li><a href="#comm">Comm</a></li></ul></blockquote><h4 dir="ltr"><a href="%3C/a"></a></h4>',
'<p><a href="//a"></a><a href="https://b/37"><em>asdf</em><em>&nbsp;Help Article</em></a></p>',
]
tests.forEach(convertHtmlToBlocks)
```

```
{
  type: 'Text',
  text: { text: 'Upgrading/Downgrading', hyperlink: 'https://url' }
} undefined
/home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converters/text.js:238
        if (block.text && /\s+/.test(block.text.text)) {
TypeError: Cannot read properties of undefined (reading 'text')
    at /home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converters/text.js:238:19
    at Array.forEach (<anonymous>)
    at shrinkTextBlockWhiteSpaces (/home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converters/text.js:237:12)
    at postProcessTextBlocks (/home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converters/text.js:167:5)
    at generateParagraph (/home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converters/paragraph.js:36:42)
    at generateParagraphBlock (/home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converters/paragraph.js:9:23)
    at /home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converter.js:36:64
    at Array.forEach (<anonymous>)
    at convertParsedHtmlToBlocks (/home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converter.js:25:14)
    at convertHtmlToBlocks (/home/jm/repos/export-elevio-kb-to-genesys/src/export_elevio_kb_to_genesys/node_modules/knowledge-html-converter/dist/converter.js:20:12)
Node.js v20.8.0
```

**Comment by tmelko-genesys** [comment]
The exact cause of the error is the empty `<a>` tag, for example: `<a href="https://url"></a>`. Thanks for pointing that out, I'll add a fix to cover that scenario, but meanwhile you could try to ensure that there is at least some content in all <a> tags and then multiple links in a paragraph shouldn't cause a problem.

On the other hand, there are quite a few limitations because of the json schema in which we store article content:

1.
`'<p><a href="https://url" rel="noopener noreferrer" target="_blank">Upgrading/Downgrading</a><a href="https://url"> hello</a></p>'`
=>
```
[
  {
    "type": "Paragraph",
    "paragraph": {
      "blocks": [
        {
          "type": "Text",
          "text": {
            "text": "Upgrading/Downgrading hello",
            "hyperlink": "https://url"
          }
        }
      ],
      "properties": {
        "fontType": "Paragraph"
      }
    }
  }
]
```

The `rel` and `target` attributes are not parsed at the moment, so the two links stripped of those will look as having the same attributes (same href) to the parser and it will merge them into one concatenating their texts.

You can have a look at the contract of the create/update variation API endpoints here: https://developer.genesys.cloud/devapps/api-explorer#post-api-v2-knowledge-knowledgebases--knowledgeBaseId--documents--documentId--variations by filtering to Knowledge and:
- POST /api/v2/knowledge/knowledgebases/{knowledgeBaseId}/documents/{documentId}/variations
- or
- PATCH /api/v2/knowledge/knowledgebases/{knowledgeBaseId}/documents/{documentId}/variations/{documentVariationId}

See the `body` property to have an idea what is supported currently.

2.
The variations API only accepts absolute hyperlink URLs starting with "https://".
I added code to the converter to ignore anchors (href="#id") since the schema doesn't support that. Other urls, like `href="//a"` and `href="%3C/a"` will pass through the converter, but they will eventually be rejected by the create/update variation API endpoints.

**Comment by jm-nab** [comment]
Thanks, I'll take a look at this and see what I can do on my end.
